development:
  adapter: postgresql
  encoding: unicode
  database: synergy_dev
  pool: 5
  username: pk60905
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: synergy_test
  pool: 5
  username: pk60905
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: synergy_production
  pool: 5
  username: pk60905
  password:  